# Numpy Basics: Arrays & Vectorised computation

## NumPy ndarray - multidimensional array object

ndarray has:
- all elements are of the same type
- every array has a shape - size of each dimension of the array
- every array has a dtype - the data type of the arry

In [2]:
import numpy as np

In [3]:
data = np.random.randn(2,3)
data

array([[ 0.83481104,  0.72119991,  0.15104261],
       [-0.68730656, -1.08747995,  0.09046824]])

In [4]:
#shape of the array
data.shape

(2, 3)

In [5]:
#data type of the array
data.dtype

dtype('float64')

**Creating ndarrays**

In [ ]:
# array function
# accepts any sequence-like object and produces a new NumPy array

data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
# nested sequences like a list of equal-length lists will become a multidimensional array

data2 = [[1,2,3,4], [5,6,7,8]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
#finding out the dimensions of an array
# use ndim
arr2.ndim

2

In [9]:
#finding out the shape of an array
#use shape

arr2.shape

(2, 4)

The functions zeros, ones and empty also make arrays. You just have to pass the dimension to it

In [10]:
#zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#empty
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
#Numpy has a built in function similar to the python range function
#arange

np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Data types for ndarrays**